### PR TITLE
docs: add main page UI picture

### LINKED ISSUE #11: Add main page mockup UI
Please add mockup UI Readme

### PR DESCRIPTION
**Pull request by Kvaibhav01**
Add the main page UI picture. It resolves issue #11

### CODE REVIEW

**Comment by Ckbhatia** [comment]
Please update message. Write message in present tense.
For more info: You can read Udacity GIT Style Guide.

**Comment by RuhanRK** [comment]
Yes we should follow GIT commit guide,, https://udacity.github.io/git-styleguide/ It'll help us to write nice and clean commit messsages

**Comment by RuhanRK** [comment]
And @Kvaibhav01 you have to add xd file, because we need those svg designs

**Comment by Kvaibhav01** [comment]
@RuhanRK. I've given them to @Ckbhatia in DM.

**Pull request merged**
