### PR TITLE
Implement the main page

### LINKED ISSUE #8: Implement the Main page
Please implement the **Main page** as **UI** available at slack.
You can ping me to assign you for a particular task.
The **slack** decision will be final.

### PR DESCRIPTION
**Pull request by revanthgss**
- Added the navbar component
- Implemented responsive home page
- Added route for home page

Deployment: http://gis-react-app.surge.sh/

Closes #8

### CODE REVIEW

**Review by Ckbhatia — CHANGES_REQUESTED** [review]
There are some problems. Needs to be reviewed before merge this.
I request all to submit bugs and other problems here if possible.
Also, it can be shared in slack.

**Comment by Kundan28** [comment]
gis
I think the line just above the "What we do ?" is not required as it's overlapping with the text for some of the devices.

**Comment by Kundan28** [comment]
@revanthgss  You can add animation to the Hamburger icon.

**Review by Kundan28 — COMMENTED** [review]
gi
I think the line just above "What we do ?" should be removed. As it's overlapping with the text in some of the devices.
And animation to the Hamburger icon could be added too.

**Comment by revanthgss** [comment]
@Ckbhatia 
The changes are made according to the reviews.
But I couldn't solve two issues.
- The svg's are loading late.
- @Kundan28 The thin line you were mentioning is not added by me. I came to know that it is the painting issue of chrome for svg's. In edge, it is not showing the thin line.

**Comment by Kvaibhav01** [comment]
Here are a few changes to be done:

- Change `font-family` to SF Pro Display.
- Add some `padding` around the nav bar and GIS logo text
- Align the heading properly.
- Remove the default link underline in texts (like in Fork On GitHub, nav bar items).
- Add `bottom-border` property to the current page/section (in Home text).
- Add some more breathing space to the card layout in the What We Do section.
- In mobile devices, that wave shape doesn't look great. Either remove it or change it to simply a rectangular shape/use it somewhere else.

**Comment by Ckbhatia** [comment]
It looks fine now after the updates.
We will check further more after this PR get merged.

**Pull request merged**
